#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   Displays "Hi" before "Best School" on the 9th interation

i=0
while [ $i -lt 10 ]
do
if [ $i -eq 9 ]
then
echo "hi"
fi
 echo "Best School"
  (( count++ ))
done

