#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hours=0
minutes=1
while [ $hours -lt 12 ]
do
 echo "Hour: $hours"
 while [ $minutes -lt 59 ]
 do
  echo"$minutes"
  (( minutes++ ))
 done
 (( hours++))
done
